### PR TITLE
[SIS-024] Home and Libary Header

### LINKED ISSUE #24: [SIS-024] Home and Library header
> As a user of the Sistema Lesson Planner, I want to be able to see the Sistema logo and access the settings page from the Home or Library page.

## Technical Information

_Note: When you start working on this, [[SIS-029] Add initial navigation and screens](https://github.com/uoftblueprint/sistema/pull/30) should be merged. Please ping @yuemily24 if it's not._ 

- [ ] Create a new directory `/src/components/` and a new file `Header.js`
- [ ] Implement a header component to be shared between the Library and Home page
- [ ] Implement a dummy "Settings" button. By dummy, we mean `onPress `doesn't have to do anything. (You may need to ask designers for the gear icon. Ignore the bear placeholder.)
- [ ] Place any logos, icons, and images in `/assets`
- [ ] Place the header in `Library.js` and `Home.js`

[Figma wireframe.](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=97%3A13579&t=ourMQysTzVpxerGI-0) Here's the designer's design for the Home page (ignore the bear placeholder).

image

**Good Resources:**

[Image](https://reactnative.dev/docs/images)

- _Note:_ There are multiple ways of manipulating images in React. The default `Image` type may not be the best case for your needs. Play around with it and change types as needed.

[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 

[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering

### PR DESCRIPTION
**Pull request by MinGi-K**
# Description

Implemented Home and Library Headers.

Ticket #24 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [ ] I have linked my issue/ticket on the project board to this PR
- [ ] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have tested that my feature works as expected on Android and iOS. If you are a Windows dev, please request a Mac dev to run your branch. If it's a front-end change, I have attached screenshots of what the result looks like on both platforms. 

Screen Shot 2023-01-01 at 6 25 16 PM
Screen Shot 2023-01-01 at 6 25 11 PM

### CODE REVIEW

**Review by helenaglow — APPROVED** [review]
The headers look good to me! 

The only thing I noticed is that there seems to be a weird issue between iOS and android for "Recently added activity cards" centering but I don't think that is your problem (just thought I should mention).

**Review by harmitgoswami — APPROVED** [review]
LGTM o7

**Comment by yuemily24** [comment]
Heyo, please change your open PR to use new SVG package. See [documentation](https://github.com/uoftblueprint/sistema/wiki/SVG-guide) on how to use it in our repo here.

**Review by harmitgoswami — APPROVED** [review]
lgtm o7

**Review by ramyzhang — APPROVED** [review]
perfect! thank you mingi!

**Pull request merged**
