### PR TITLE
[SIS-052] Edit lesson plan name

### LINKED ISSUE #52: [SIS-052] Edit lesson plan name
> As a user of the Sistema Lesson Planner, I want to be able to edit my lesson plan (LP) name in the LP editor. 

_Jan 24 Update:_
- Default LP name: “Date”: Lesson Plan
- Ex. “Jan 19, 2023: Lesson Plan”
- Ex. “Jan 19, 2023: Lesson Plan (1)” ← if making another lesson plan on the same day

## Technical Information

- [ ] Create a react state to hold the LP name in 
- [ ] Convert the title into a textbox that the user can edit 
- [ ] Editing the name will change the react state
- [ ] Decide on a character limit for the LP name and enforce it! A user won't be able to type in the textbox past that limit. 
- [ ] The name should ellipse if it's cut off by the right hand side icons (but not when the user is editing it)

## Design

[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=51%3A13021&t=uBWLplRiS9RKkpMh-0)

image

## Resources
[TextInput](https://reactnative.dev/docs/textinput)
[Stylesheet](https://reactnative.dev/docs/stylesheet)

### PR DESCRIPTION
**Pull request by kurtislaw**
# Description

Made it so the lesson plan can be editted

Ticket #

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] 
# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [x] I have linked my issue/ticket on the project board to this PR
- [x] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by yuemily24 — CHANGES_REQUESTED** [review]
I tried running this on Android, so I can't say if this is the same for iOS but there are some few features missing, please address:

- Clicking on the pencil/edit icon should automatically open/put focus on the TextInput
- When the lesson plan name input loses focus (eg. the user presses enter, or taps outside the box), the title should display the title from the beginning. For example, if the whole title was "This is a very long long long long title" it would display "This is a very long..."
- Don't forget to ellipse the title once it can't be displayed past the allowed length
- There is a max character allowed. Users shouldn't be able to type past a character limit (it should be on the Figma comments, if not, check with designers)

Please let me or the designers know if you have any questions about expected behaviour.

**Comment by ramyzhang** [comment]
@kurtislaw, hey how is this going?

**Comment by ramyzhang** [comment]
not working consistently on ios on my machine and not working on android at all... very strange :( emily and i will take a look at this during today's work session!

**Comment by ramyzhang** [comment]
fixed but still some styling things for icon sizes. otherwise the android edit bump is fixed now

**Pull request merged**
