### PR TITLE
[SIS-002] Sarah's first PR

### PR DESCRIPTION
**Pull request by Lemiex**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Ticket # (issue/ticket number)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation changes 
- [ ] Style (formatting, missing semi colons, etc; no production code change)
- [ ] Refactor (refactoring production code, eg. renaming a variable)
- [ ] Chore (updating grunt tasks etc; no production code change)
- [ ] Build (changing build dependencies, updating packages, etc.)

# Checklist:

- [ ] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [ ] I have linked my issue/ticket on the project board to this PR
- [ ] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by helenaglow — DISMISSED** [review]
Looks good to me!

**Review by azamat-khamidov — APPROVED** [review]
Looks good to me!

**Review by helenaglow — APPROVED** [review]

**Review by azamat-khamidov — CHANGES_REQUESTED** [review]
As Helena said, there will be a merge conflict with Harmit's PR. Consider adding your name to line number 8.

**Review by helenaglow — CHANGES_REQUESTED** [review]
I think line 9 would be better because Min Gi is line 8

**Review by azamat-khamidov — APPROVED** [review]
Looks good!

**Review by helenaglow — APPROVED** [review]
Looks great! Yay!

**Pull request merged**
