### PR TITLE
[SIS-021] Bottom navbar styling

### LINKED ISSUE #21: [SIS-021] Bottom navbar styling
> As a user of the Sistema Lesson Planner, I want to be able to clearly understand which button on the navigation bar to click to go to the Library page.

**Technical Information:**

Implement the designer's design for the Navbar's Library button. It should look like the below (grey and underlined when the page is in focus):

Image

**Colours:**

#B8CFE4
#685777
#000000

_Note: When you start working on this, [[SIS-029] Add initial navigation and screens](https://github.com/uoftblueprint/sistema/pull/30) should be merged. Please ping @yuemily24 if it's not._ 

1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 
3. Inside `App.js`, edit the bottom tab navigation so that all three tabs display an icon. When the screen is in focus, the icon should be a different colour. 
4. Set the background colour of the bottom navbar and change the icon scale and height of the navbar to the correct size. The end result should look like the screenshot above.

_In your PR, please screenshots of what the final result is on iOS and Android._ 

**Good Resources:**

These packages should already be part of your build in`package.json`. Make sure to run `git pull` and `yarn --frozen-lockfile` to rebuild and download the required navigation and SVG packages if you haven't done so already.

[React Navigation website](https://reactnavigation.org/)
[React Navigation—Tab-Based Navigation](https://reactnavigation.org/docs/tab-based-navigation/)
[React Native SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md)

### PR DESCRIPTION
**Pull request by kurtislaw**
# Description

Styled the nav bar. The underline has not been implemented though. New dependency: react-native-svg-transformer

Preview

Ticket #21

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [x] I have linked my issue/ticket on the project board to this PR
- [x] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [x] I have tested that my feature works as expected on Android and iOS. If you are a Windows dev, please request a Mac dev to run your branch. If it's a front-end change, I have attached screenshots of what the result looks like on both platforms.

### CODE REVIEW

**Review by Lemiex — APPROVED** [review]
Looks pretty good to me! It seems like your nav is slightly shorter than the one in the designs though, not sure just eyeballing it!
Also for your second picture, would it be possible to fill the screen to the bottom with the nav bar?

**Comment by yuemily24** [comment]
Added underline and made tabIcon into component with this [commit](https://github.com/uoftblueprint/sistema/pull/62/commits/3f47940c5b181d7e22ab3498844556f22a0c3e48)
Screenshot (256)

**Review by MinGi-K — APPROVED** [review]
Good work man! Maybe like Sarah suggested, you could try make flush the navbar down in the os version, maybe set margin bottom of navbar to 0? Also the line thickness of the home svg seems quite a bit thinner than the other 2, not sure if that is by design!

**Comment by yuemily24** [comment]
Can you comment on the changes ppl suggested above? And resolve the merge conflicts, thanks! Then, request me to merge.

**Comment by kurtislaw** [comment]
Fixed android padding and updated screenshot

**Review by yuemily24 — APPROVED** [review]
LGTM! Thanks for making sure it works on both Android and iOS. As a heads-up, I believe Mingi is implementing a json file in the future to standardize our colors so that instead of using string hex codes, we'll just insert a constant. And there are def a few in here that could be added @MinGi-K!

**Pull request merged**
