### PR TITLE
[SIS-158] Wifi warnings

### PR DESCRIPTION
**Pull request by yuemily24**
# Description

Display wifi warning overlay in the following scenarios:

- In Home
   - App opens and wifi is already off
   - User is on the page and wifi suddenly turns off 
   - Tries to press refresh button to grab new featured activity cards
- In Add Activity Card page
    - User navigates to this page from the Editor and wifi is already off
    - User is on the page and wifi suddenly turns off 
    - Tries to press 'Add Card' (card previews can be cached from useQuery but can't be downloaded)

Screenshot 2023-08-06 at 8 25 03 PM
Screenshot 2023-08-06 at 8 40 55 PM

Tested on Android. New package. Please re-run `yarn`.

### CODE REVIEW

**Comment by yuemily24** [comment]
@ramyzhang Sorry my Xcode is still broken. 😭 Could you test around with it on iOS? New package [netinfo](https://github.com/react-native-netinfo/react-native-netinfo#using-react-native--060) added, it's going to need you to run `npx pod-install` inside `/ios` to set up on iOS. And `yarn` before that obv. Thanks! 🙏

**Review by ramyzhang — CHANGES_REQUESTED** [review]
hmmm there's no way of actually turning the wifi off for the iphone simulator so i just turned off my laptop's wifi, and the error overlay only displayed once i turned it back on. could you look into this? it does seem like the iphone simulator is notoriously bad for testing network changes, so we should probably try it on a real device, but i don't have access to an iphone :(
EDIT: so yeah it seems like turning on and off the host device's wifi is pretty unreliable for testing this, so that's probably why the overlay is only triggered a little after the internet's back on. maybe we can just merge this for now and open a separate ticket for iphone testing? i can try it when i go to my parents place, my mom has one

**Comment by yuemily24** [comment]
> hmmm there's no way of actually turning the wifi off for the iphone simulator so i just turned off my laptop's wifi, and the error overlay only displayed once i turned it back on. could you look into this? it does seem like the iphone simulator is notoriously bad for testing network changes, so we should probably try it on a real device, but i don't have access to an iphone :(

Ok will investigate! Also the first answer in this stackoverflow https://stackoverflow.com/questions/4808433/is-it-possible-to-disable-the-network-in-ios-simulatorI'm dying

**Comment by ramyzhang** [comment]
> > hmmm there's no way of actually turning the wifi off for the iphone simulator so i just turned off my laptop's wifi, and the error overlay only displayed once i turned it back on. could you look into this? it does seem like the iphone simulator is notoriously bad for testing network changes, so we should probably try it on a real device, but i don't have access to an iphone :(
> 
> Ok will investigate! Also the first answer in this stackoverflow https://stackoverflow.com/questions/4808433/is-it-possible-to-disable-the-network-in-ios-simulatorI'm dying

I SAW THAT HAHAHAH I CRIED I COULDNT TELL IF THEY WERE SERIOUS OR NOT

**Pull request merged**
