### PR TITLE
[SIS-053] Lesson plan options menu

### LINKED ISSUE #53: [SIS-053] Lesson plan options menu
> As a user of the Sistema Lesson Planner, I want to pull up an options menu to see what I can do with my lesson plan (LP). 

## Technical Information

This menu is used both in the LP Editor and Library, with the exception of the middle button and menu title. Make it a reusable component between the two. 

Tapping outside of the menu or on the 'X' should close it (see Resources).

You'll be blocked by [[SIS-051]](https://github.com/uoftblueprint/sistema/issues/51) from adding it to the Library page. 

## Design

The button borders are kinda thick for the inner ones because they're doubled up. Try to avoid that. 

### LP editor
[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=138%3A14431&t=uBWLplRiS9RKkpMh-0)

- [ ] Inside LP editor: tapping on "Add to Favourites" should change the icon and text, and a pop up "Lesson plan added to favourites" should briefly appear. Tapping on it again should change it back and a different pop up should appear. 
- [ ] Other dummy buttons (`onPress `does nothing)

image
image
image

### Library
[Figma](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=280%3A15467&t=uBWLplRiS9RKkpMh-0)

- [ ] Other dummy buttons (`onPress` does nothing)

image

## Resources
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 
Although, check in with this [ticket](https://github.com/uoftblueprint/sistema/issues/47) first to see if a new, easier package can be used. 

### Overlay tapping to close
Make the "overlay" an entirely new screen in `EditorNavigator`. That way you can add on the entire screen an onPress function to `navigation.goBack()` to the previous screen. For an example, see last year's [Period Purse screen](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/home/pages/SelectLogOptionOverlay.js) (ask Emily if you have any questions, since I wrote the code for that part.
OR Dig around for some packages that might help!

### Dynamic rendering (optional)

You may or may not want to use this. Up to you. Check out this example code [here](https://github.com/uoftblueprint/the-period-purse/blob/develop/tpp-app/src/info/Info.js):
```javascript
const optionData = [
    {
        name: "Export Lesson Plan",
        image: <SaveIcon/>,
        screen: STACK_SCREENS.EXPORT_LESSON_PLAN
    },
    {
        name: "Add to Favourites",
        image: <HeartIcon/>,
        screen: STACK_SCREENS.ADD_TO_FAVOURITES
    },
    ...
]
```
And then we can do:
```javascript
  <View style={styles.containerRow}>
      {optionData.map((option, i) => { return (
          <LessonPlanOption
              key={i}
              name={option.name}
              image={option.image}
              onPress={() => navigation.navigate(option.screen)}
          />
      )})}
  </View>
```
This will let you dynamically render components (text modules) based on an array.

### PR DESCRIPTION
**Pull request by helenaglow**
# Description

This pull request is for the library and lesson plan option menu.  The two different versions are interchangeable, as required. I have also tested on different sized android phones to ensure it looks and functions the same.

**Some instructions:**
Calling the screen with isLessonPlanner = true will result in the lesson plan options. If you call the screen and set it to false, you can also input lessonPlanName, the screen will change accordingly. The default name right now is "Lesson Plan Name" which is initialized in the EditorNavigator. 

**Example:**
- navigation.navigate('Lesson_Plan_Editor_Menu', { isLessonPlanEditor: true })

- navigation.navigate('Lesson_Plan_Editor_Menu', { isLessonPlanEditor: false, lessonPlanName: 'Helena's Plan'})

**isLessonPlanEditor == true**
lessonPlanEditorOptions

**isLessonPlanEditor == false**
libraryOptionsFullScreen

addedToFavorites

removedFromFavorites

Ticket #53

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change
 which adds functionality)

# Checklist:

- [X] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [X] I have linked my issue/ticket on the project board to this PR
- [X] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (if required)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by helenaglow** [comment]
There is a problem with the header let me figure that out

**Review by harmitgoswami — APPROVED** [review]
LGTM!! hefty ticket & you implemented it pretty elegantly, good job!

**Comment by ramyzhang** [comment]
@MinGi-K review pls! :D

**Review by MinGi-K — APPROVED** [review]
Yep, it works on my end too!! Looks good and I love the branch name. Amazing job!!

**Review by ramyzhang — CHANGES_REQUESTED** [review]
Screenshot 2023-01-29 at 5 44 35 PM

the options menu is floating on this device :(

**Comment by ramyzhang** [comment]
checked over the code, otherwise looks clean! great job! just take a look at above issue :D

**Comment by ramyzhang** [comment]
fixed! has to be tested on android still

**Comment by helenaglow** [comment]
Checked on android and works correctly!

**Review by ramyzhang — APPROVED** [review]

**Pull request merged**
