### PR TITLE
[SIS-070] Service file boilerplate for RNFS calls

### LINKED ISSUE #70: [SIS-070] Service file boilerplate for RNFS calls
> As a user of the Sistema Lesson Planner, I want all my lesson plan data to be stored locally for privacy.

## Technical Information

Create template service files for components to make calls to local storage endpoints.
- [ ] Create file with sample function headers
- [ ] Write wiki page for debugging + checking contents of local storage

## Resources
[React-Native-FS Github](https://github.com/itinance/react-native-fs)

### PR DESCRIPTION
**Pull request by ramyzhang**
# Description

Wrote Local.js for writing base calls to RNFS (including all the ugli Promises and ten million .thens), and added template function headers for LessonPlanService.js
Backend PR so no screenshots!

TODOs left:
- [x] Write docstrings with more clarity on parameter types and return types
- [x] Add in remaining relevant RNFS calls
- [x] Write Wiki page on how to test whether your RNFS call is working or not + check contents of files
- [x] Write better console.logs

# Ticket #70 

https://github.com/uoftblueprint/sistema/issues/70

# Type of change
New feature (non-breaking change which adds functionality)

# Checklist:
 - [x] My PR title is formatted as [SIS-<issue number>] <issue name> (eg. [SIS-010] Create UI button)
 - [x]  I have linked my issue/ticket on the project board to this PR
 - [ ] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
 - [x] My code follows the style guidelines of this project
 - [x] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation (if required)
 - [x] My changes generate no new warnings
 - [ ] I have tested that my feature works as expected on Android and iOS. If you are a Windows dev, please request a Mac dev to run your branch. If it's a front-end change, I have attached screenshots of what the result looks like on both platforms.

### CODE REVIEW

**Comment by ramyzhang** [comment]
RNFS calls are working rn but everything's kinda ugly and need a better way of testing

**Comment by ramyzhang** [comment]
remaining TODO: write Jest files

however, as it is it is ready to be developed on and it's relatively easy to test manually

**Comment by ramyzhang** [comment]
additional TODO: 
- [x] add favouriting and unfavouriting endpoint
- [x] make sure signatures are consistent with wiki
- [x] add RNFS.exists() endpoint
- [x] make a reference for the path constants in RNFS in Local.js so we don't have to require RNFS in LessonPlanService.js

**Comment by ramyzhang** [comment]
@yuemily24 hayo finally ready for review, could u check if this runs?

**Review by yuemily24 — APPROVED** [review]
Oh my god this is so thorough I basically left the Drive group to their whims LOL

**Pull request merged**
