### PR TITLE
[SIS-023] Blank lesson editor

### LINKED ISSUE #23: [SIS-023] Blank LP Editor Page
> As a user of the Sistema Lesson Planner, I want to be able to access a page that shows me the Lesson Plan Editor page, where I can create my own Lesson Plans with Sistema teaching materials!

Style basic components for the LP Editor page! _Note: When you start working on this, [[SIS-029] Add initial navigation and screens](https://github.com/uoftblueprint/sistema/pull/30) should be merged. Please ping @yuemily24 if it's not._ 

**Technical Information:**

Inside `packages/mobile/src/editor/screens/LessonPlanEditor.js`:
- [x] Add colours
- [x] Add text headings
- [x] Implement dummy "Add ..." buttons
- [x] Implementing text box input!
- [x] Implement dummy save button
- [x] Put all of these buttons and headings in a `ScrollView` (becomes scrollable as lesson plan content is added)

By _dummy_, we mean `onPress` doesn't have to do anything. 

[Figma wireframe.](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=51%3A13021&t=IapeORhvrLZUkwRP-0) Here's the designer's design for the Lesson Plan Editor page (you don't have to implement this design _nor all the buttons and header at the top of the editor yet_, this is just to get an idea of what it will look like.) 

Image

**Colours:**

#FFFAF5
#685777

**Good Resources:**

[View](https://reactnative.dev/docs/view)
[TouchableOpacity](https://reactnative.dev/docs/touchableopacity)
[Flexbox](https://reactnative.dev/docs/flexbox) for centering
[Stylesheet](https://reactnative.dev/docs/stylesheet)
[ScrollView](https://reactnative.dev/docs/scrollview/)
[SVG docs](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) -- for icons
1. Go to the Figma [hi-fidelity wireframe](https://www.figma.com/file/kSZduD0A5hk8sHmvqiC7DE/Sistema-Hi-Fidelity-Designs-%2B-Design-System?node-id=42%3A12578) to export the icons as SVGs. On the right sidebar, Design > Export > SVG. 
2. See example usage of SVGs [here](https://github.com/uoftblueprint/sistema/blob/097f08271e46bce430453430d04719ecff60a771/packages/mobile/assets/HomeIcon.js). 

[TextInput](https://reactnative.dev/docs/textinput) -- for comments/textbox input

### PR DESCRIPTION
**Pull request by Lemiex**
Blank lesson edit with dummy buttons and scroll view

Changes:
 Add colours
 Add text headings
 Implement dummy "Add ..." buttons
 Implementing text box input!
 Implement dummy save button
 Put all of these buttons and headings in a ScrollView (becomes scrollable as lesson plan content is added)
Screen Shot 2022-12-06 at 12 09 57 AM
Screen Shot 2022-12-06 at 12 09 43 AM

### CODE REVIEW

**Review by helenaglow — APPROVED** [review]
Looks good to me! Have you tried testing on different sized screens?

**Comment by ramyzhang** [comment]
the padding looks a tad wonky on mine, could you double check? also no shadows :( this is my iphone 13, ios 15.5
Screen Shot 2022-12-04 at 9 25 44 PM (1)

also, emily tested it on android and there's some padding issues with the header:
IMG_20221205_194544

**Comment by ramyzhang** [comment]
really nice! nice job!! :) sorry about the fonts, apparently it isn't working on emily's android build either. we'll open a separate ticket for this so don't worry about it for now!

pls review! @kurtislaw

**Review by kurtislaw — APPROVED** [review]
Looks good to me! The changes from the previous commit are good as well.

**Review by ramyzhang — APPROVED** [review]
edited some asset paths that weren't directing to the correct directory. also, the poppins fontfamily started breaking in my build too (???) so ... i removed it from the header file and it stopped breaking.

TODO:
- [ ] fix font family shenanigans
- [ ] padding for the "+" buttons still has the same problems as the screenshot i attached before, but we can fix that in a later ticket (i can help if you can't install the iphone 13 sim)

**Pull request merged**
